export const contactEmail = "work.mmstudio@gmail.com";
export const contactHref = `mailto:${contactEmail}?subject=${encodeURIComponent("Información sobre un proyecto")}&body=${encodeURIComponent("Hola, Miros:\n\nHe visto tu trabajo en la web de MM WORKS y me gustaría pedirte información para un proyecto.\n\nMi idea es:\n\n¿Podemos hablar sobre las opciones y el presupuesto?\n\nGracias.")}`;

export const projects = [
  { id: "juan-domingo", name: "Juan Domingo", category: "Experiencia digital / Running culture", title: "La cultura del running también se corre en digital.", description: "Una tienda de running, una comunidad y todo lo que ocurre entre una salida y la siguiente. El territorio del proyecto une comercio, contenido y cultura del deporte.", color: "orange" },
  { id: "brket", name: "BRKET", category: "Producto digital / Sports tech", title: "El juego empieza mucho antes del partido.", description: "Organizar la competición también forma parte de la experiencia. BRKET lleva el foco a los torneos y al producto que conecta cada encuentro.", color: "violet" },
  { id: "tramicalma", name: "TramiCalma", category: "Servicio digital / SEO", title: "Menos vueltas. Más claridad.", description: "Un servicio digital que parte de una necesidad concreta: entender el siguiente paso. Claridad de contenido, presencia en buscadores y una experiencia fácil de seguir.", color: "sage" },
  { id: "hausfix", name: "Hausfix", category: "Presencia digital / Negocio local", title: "Estar donde empieza la búsqueda.", description: "Presencia digital conectada con la realidad de un negocio local: explicar lo que hace, facilitar que lo encuentren y abrir una conversación.", color: "orange" },
  { id: "buddypadel", name: "BuddyPádel", category: "Producto / Software para clubes", title: "Más tiempo en la pista.", description: "El club como punto de partida de un producto digital. Una exploración de las herramientas que acompañan su día a día y la experiencia de sus jugadores.", color: "violet" },
];

export const disciplines = [
  { name: "Dirección creativa", index: "01", text: "Encontrar la idea que merece existir. Definir el concepto, el tono y la dirección de cada pieza para que todo tenga una intención." },
  { name: "Identidad & marcas", index: "02", text: "Una marca tiene que reconocerse y tener algo que decir. Creamos su lenguaje visual y verbal, y un sistema capaz de crecer con ella." },
  { name: "Webs & experiencias", index: "03", text: "Un lugar propio en internet. Diseñamos y desarrollamos webs que explican bien, se sienten distintas y hacen fácil dar el siguiente paso." },
  { name: "Productos & sistemas", index: "04", text: "Convertimos procesos e ideas en herramientas que se pueden usar. Del primer flujo al producto, con diseño y desarrollo en la misma mesa." },
  { name: "Campañas & contenido", index: "05", text: "Conceptos que funcionan en una pantalla, en la calle o en un feed. Piezas con una idea detrás y una identidad que se mantiene al cambiar de formato." },
];

export const articles = [
  { id: "idea-first", category: "MM//POV", title: "Sin una idea, solo es decoración.", label: "01 / Punto de vista", paragraphs: ["Antes de elegir una tipografía, hay una pregunta: ¿qué tiene que decir esta pieza? Si no podemos responderla en una frase, todavía no toca diseñar.", "Una idea no es una capa de explicación que añadimos al final. Es lo que decide el encuadre, el ritmo, el material y también lo que sobra. Hace que dos piezas distintas pertenezcan al mismo mundo.", "Nuestra prueba es simple: quitar los efectos. Si lo que queda sigue diciendo algo, hay una base sobre la que trabajar."] },
  { id: "break-format", category: "MM//BREAKDOWN", title: "Una idea que no cabe en el molde.", label: "02 / Dentro del proceso", paragraphs: ["La portada de MM WORKS nace de una tensión: una estructura rígida y una idea que necesita pasar. La placa representa el formato. La pieza azul, lo que todavía no tiene sitio.", "La imagen se ha desarrollado con generación de imagen y dirección creativa. La luz, el material y la presión cuentan la misma historia. No hace falta añadir diez símbolos si un solo gesto explica el concepto.", "Después llega la web: la tipografía permanece legible, el scroll sigue siendo natural y la imagen deja espacio al mensaje. El concepto tiene que sobrevivir al uso."] },
  { id: "physical-digital", category: "MM//LAB", title: "De la materia a la pantalla.", label: "03 / Experimento visual", paragraphs: ["El metal tiene peso. El papel tiene pliegues. Una pantalla no tiene por qué borrar esas cualidades. Nos interesa traducirlas, no simular un escritorio lleno de objetos.", "En THE IDEA MACHINE, una hoja arrugada entra en una prensa y sale convertida en una pieza sólida. Es una imagen conceptual, no una máquina real: una forma de contar cómo una intuición toma estructura.", "La mezcla funciona cuando cada material tiene una razón para estar. Lo físico pone la tensión; lo digital permite recorrerla."] },
];
